### ISSUE TITLE
Release version 1.16.2

### ISSUE THREAD

**Issue by pcdavid** [eclipse/gmf-runtime#38]
## Milestones

- [x] Bump version
  - [x] Modified bundles => bump to x.y.(z+1)
  - [x] All features => 1.16.2
- [x] Promote the build as a `milestone` and tag it

## Actual release

- [x] Promote the build in `releases`: https://download.eclipse.org/modeling/gmp/gmf-runtime/updates/releases/R202311130907/
- [x] Tag the commit as `v1.16.2` and `R1_16_2`
- [x] Contribute the new version to the SimRel: https://github.com/eclipse-simrel/simrel.build/commit/615ff78d4bdff9ddcf41cd420043e495007105f0
